# PlateVision — Configuration YOLOv8
# Généré automatiquement par data/prepare_datasets.py
path: C:\Users\basil\Desktop\Projet_IA\platevision\data\processed
train: images/train
val: images/val
test: images/test

nc: 1
names:
  0: plaque_immatriculation
